server.port=8081
spring.profiles.active=dev

# Common config
spring.main.allow-bean-definition-overriding=true
spring.jpa.open-in-view=false

# Swagger configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
